#Script prepared to help update some climate data
#Prepared as part of C16049 Selwyn District Council Climate variability
#Tim Kerr
#Aqualinc Research Ltd.
#August 2016

#The main purpose of this script was to update climate files based on relationships with other sites.
#The script consists of four functions
#returnmonthlyAdjusters compares two timeseries of data and returns monthwise ratios or differences depending on whether the data are for rain of temperature
#multidate checks a date series for different date formats and makes them consistent
#stripoutoriginals pulls out the data from an "extended" data series that is from observations, not correlations to other sites. Designed to work on the data that is generated by the Peter/Jono climate data extension software
#updateestimates takes two sites, their monthwise relationships and applies it to days missing in the first site but existing in the second site

#The actual work is done in the few lines at the end of this file.
#Note that these scripts have no error handling and were written for single use work that has already ocurred.


library(zoo)
library(hydroTSM)

returnmonthlyAdjusters <- function(siteDataFrame,stationDataFrame,dataType) {
  #returns monthly ratios of TS1(site)/TS2(station) average monthly values
  newdates <-as.Date(intersect(siteDataFrame$Date,stationDataFrame$Date))         #Find the dates that match
 
  MatchingSiteData<-siteDataFrame[match(newdates,siteDataFrame$Date),2]          #get the data from the site of interest (TS1 or time series 1)
  MatchingStationData<-stationDataFrame[match(newdates,stationDataFrame$Date),2] #get the data from the correlating site (TS2 or timeseries 2)
  
  #Put it all together as a zoo object to work with the dates
  MatchingData <- zoo(cbind(SiteData=MatchingSiteData,StationData=MatchingStationData),order.by = newdates)
  
  #obtain the TS1(site) and TS2 (station) monthly averages in order:
  matchingStationMonthlyAverages <- monthlyfunction(MatchingData[,"StationData"], FUN =mean) #get the month averages of the data from the site of interest (TS1)
  
  matchingSiteMonthlyAverages <- monthlyfunction(MatchingData[,c("SiteData")], FUN =mean)       #get the month averages of the data from the correlating site (TS2)
  
  if (dataType == "Rainfall") {  #eg rain
    #divide one by the other to get monthly averages
    monthlyAdjusters<- coredata(matchingSiteMonthlyAverages) / coredata(matchingStationMonthlyAverages)
    
  } else if (dataType %in% c("MaxT","MinT"))  {  #eg if temperature data
    
    # subtract site(TS1) average from station(TS2) average
    monthlyAdjusters<- coredata(matchingSiteMonthlyAverages) - coredata(matchingStationMonthlyAverages)
  }
  
  return(monthlyAdjusters)
}

multidate <- function(data, formats){
  a<-list()
  for(i in 1:length(formats)){
    a[[i]]<- as.Date(data,format=formats[i])
    a[[1]][!is.na(a[[i]])]<-a[[i]][!is.na(a[[i]])]
  }
  a[[1]]
}

StripOutOriginals <- function(filename) {
  #open file
  extendedData <- read.csv(filename,colClasses = c("character","numeric",rep(NA,9)))[,1:4]
  #extendedData <- read.csv(filename,colClasses = c("character","numeric"))[,1:4]
  #select the dates with "original" in the third column
  #return the first two columns
  originalData <- extendedData[extendedData$Origin=="original",c("Date","Value")]
  #Sort out the nasty date format issue
  MonoFormatDates <- multidate(originalData$Date, c("%Y-%m-%d","%d/%m/%Y"))  #need this cause the dates have mixed formats
  originalData$Date <- MonoFormatDates
  return(originalData)
}

UpdateEstimates <- function(dataDirectory,SiteOfInterest=4881,CorrelationSite=4843,StartDate="2015-11-01",EndDate="2016-06-30",MonthAdjusters,DataType="Rain"){
  #open file
  SiteOfInterestFileName  <- file.path(dataDirectory,parameter,paste(SiteOfInterest,"extended.csv"))
  CorrelationSiteFileName <- file.path(dataDirectory,parameter,paste(CorrelationSite,"extended.csv"))
  SiteData                <- read.csv(SiteOfInterestFileName,colClasses = c("character","numeric",rep(NA,9)))[,1:4]
  CorrSiteData            <- read.csv(CorrelationSiteFileName,colClasses = c("character","numeric",rep(NA,9)))[,1:4]
  #SiteData                <- read.csv(SiteOfInterestFileName,colClasses = c("character","numeric"))[,1:4]
  #CorrSiteData            <- read.csv(CorrelationSiteFileName,colClasses = c("character","numeric"))[,1:4]
  MonoFormatDates         <- multidate(SiteData$Date, c("%Y-%m-%d","%d/%m/%Y"))  #need this cause the dates have mixed formats
  SiteData$Date           <- MonoFormatDates
  MonoFormatDates         <- multidate(CorrSiteData$Date, c("%Y-%m-%d","%d/%m/%Y"))  #need this cause the dates have mixed formats
  CorrSiteData$Date       <- MonoFormatDates
  #find missing dates in the period of interest
  DatesOfInterest         <- seq.Date(from = as.Date(StartDate), to = as.Date(EndDate), by = "day")
  SubsetSiteDataDates     <- subset(SiteData, Date >= StartDate & Date <= EndDate)$Date
  DatesToFill             <- DatesOfInterest[which(!(DatesOfInterest %in% SubsetSiteDataDates))]
  #Get correlationsite data for the missing dates
  CorrSiteDataToUse      <- CorrSiteData[which(CorrSiteData$Date %in% DatesToFill),]
  #Generate a column called month
  CorrSiteDataToUse$month <- as.numeric(format(CorrSiteDataToUse$Date,"%m"))
  #Populate a column called "adjuster" using values from the MonthlyAdjuster lookup table
  CorrSiteDataToUse$adjuster<- MonthlyAdjusters[CorrSiteDataToUse$month]
  #Apply the adjustment. Type 1 (rain) is a ratio, type 2 (temperature) is an offset
  if (DataType %in% c("Rainfall")){
    CorrSiteDataToUse$Adjusted <- CorrSiteDataToUse$Value * CorrSiteDataToUse$adjuster
  } else if (DataType %in% c("MaxT","MinT")) {
    CorrSiteDataToUse$Adjusted <- CorrSiteDataToUse$Value + CorrSiteDataToUse$adjuster 
  }
  #Now I need to update the SiteData
  #browser()
  UpDateData <- CorrSiteDataToUse[,c("Date","Adjusted")]                #Get the new values
  UpDateData$Origin <- as.factor(CorrelationSite)                       #Add in the correlating station's agent number
  UpDateData$Correlation <- rep(NA,nrow(UpDateData))                    #With NA's for the actual correlation
  colnames(UpDateData)    <- c("Date","Value","Origin","Correlation")   #Name the columns
  
  UpdatedSiteData <- rbind(SiteData,UpDateData)                         #Add the new to the old
  UpdatedSiteData <- UpdatedSiteData[order(UpdatedSiteData$Date),]                              #And re-order by the date
  return(UpdatedSiteData)
}


dataDirectory <- "G:\\ARL Projects\\Other\\C16049_SDC climate impact\\Data\\StationData"


parameter          <- "MinT"
SiteOfInterest     <- 4698
CorrelationSite    <- 4764
StartDate          <- "2015-11-01"
EndDate            <- "2016-06-30"
#Warning To get the correlations you need to use the data from Egnyte that includes the column specifiying whether it is "original" or not
#Another warning. You need to get rid of all the silly double quotes that excel sometimes puts in. Simply open in notepad and do a global replace of quotes with nothing.
#Third warning: If you open the csv files in Excel then save them, excel will muck up the date formatting. You need to specify the date format as yyyy-mm-dd before saveing.
#I should probably do that here programmatically, but I haven't. Tim
siteOfInterestData <- StripOutOriginals(file.path(dataDirectory,parameter,paste(SiteOfInterest,"extended.csv")))
CorrelationSiteData <- StripOutOriginals(file.path(dataDirectory,parameter,paste(CorrelationSite,"extended.csv")))
MonthlyAdjusters   <- returnmonthlyAdjusters(siteOfInterestData,CorrelationSiteData,dataType=parameter)
NewSiteData        <- UpdateEstimates(dataDirectory,SiteOfInterest=SiteOfInterest,CorrelationSite=CorrelationSite,
                                      StartDate=StartDate,EndDate=EndDate,MonthAdjusters=MonthlyAdjusters,DataType=parameter)
write.csv(NewSiteData,file=file.path(dataDirectory,parameter,paste0(SiteOfInterest," extended ",EndDate,".csv")),quote=FALSE,
          row.names=FALSE)
